spring:
  application:
    name: librarymanagementsystem
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management_db
    username: root
    password:
